In [2]:
import numpy as np

lst =list(range(1,25))
arr=np.array(lst)
print(type(arr))
print(type(lst))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
# creating numpy array 
arr=np.array([1,2,3,4])
lst=list(range(5))
print(lst)
print(arr)


[0, 1, 2, 3, 4]
[1 2 3 4]


In [7]:
# aranage() - used to create the array
arr= np.arange(1,25)
arr # single dimension array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [9]:
# 2d array 
arr=np.zeros((5,15))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
#2d array 
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
#2d array 
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#3d array 
arr=np.array([[[1,2,3,4],[4,5,6,2],[5,8,26,6]],[[15,65,55,52],[5,25,45,62],[15,75,25,25]]])
arr

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  2],
        [ 5,  8, 26,  6]],

       [[15, 65, 55, 52],
        [ 5, 25, 45, 62],
        [15, 75, 25, 25]]])

In [2]:
import numpy as np


In [3]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr= np.linspace(1,42,5) # linspace for the 6 values between 1 and 42
arr

array([ 1.  , 11.25, 21.5 , 31.75, 42.  ])

In [ ]:
#linspace() used to create array in the equal intervals
#reshape is used for row(5) or column(1) and linspace take 5 values between 1 to 10
arr= np.linspace(1,10,5).reshape(5,1)
arr

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [ ]:
#reshape 1d array convert 2d array 
#take reshape values as the value as the value which is multiple of 30(element in arrange)
arr= np.arange(0,30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [11]:
#arr.shape for finding to shape of element
arr.shape

(5, 6)

In [14]:
arr.reshape(3,5,2)     #3 bracket , 5 row ,2 column

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [21]:
#random initialization
# genrate the random no. between 1 and 5
arr= np.random.randint(1,5,9)
arr

array([1, 2, 2, 2, 1, 1, 1, 2, 1])

In [ ]:
# generating 2d array by using random function 
arr= np.random.randint(1,5,(5,9))
arr

array([[2, 3, 2, 4, 3, 3, 4, 2, 3],
       [1, 3, 2, 4, 3, 2, 3, 4, 3],
       [2, 4, 2, 4, 2, 2, 2, 4, 2],
       [3, 3, 4, 4, 2, 3, 1, 3, 4],
       [2, 1, 1, 4, 4, 4, 4, 4, 2]])

In [ ]:
# generating 3d array by using random function 
arr=np.random.randint(1,5,(3,4,4))
arr

array([[[1, 4, 3, 4],
        [2, 4, 1, 4],
        [2, 4, 2, 4],
        [3, 4, 4, 3]],

       [[4, 2, 4, 3],
        [4, 3, 1, 3],
        [2, 2, 4, 1],
        [3, 3, 1, 1]],

       [[2, 3, 2, 1],
        [2, 3, 1, 4],
        [1, 4, 1, 3],
        [2, 2, 4, 1]]])

In [ ]:
arr=np.random.random(10)      #generate 10 random value between 0 to 1
arr

array([0.44849098, 0.26399618, 0.90732566, 0.00705327, 0.8590036 ,
       0.77650423, 0.06140522, 0.16841147, 0.39919831, 0.96410246])

In [32]:
arr=np.random.randint(10)      #by default print 1 value between 1 to 10
arr

3

In [ ]:
arr=np.random.random((1,10))      #generate 2d by random
arr

array([[0.7744781 , 0.87519301, 0.1992193 , 0.69595145, 0.72092205,
        0.46089158, 0.38520758, 0.77985406, 0.9271952 , 0.47588685]])

In [37]:
arr=np.arange(60).reshape(10,6)   #arr.dtype is used to check data type
print(arr)
arr.dtype

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]


dtype('int32')

In [ ]:
arr=np.arange(60).reshape(10,6)   #arr.dtype is used to check data type
print(arr)
print(arr.dtype)
print(arr.ndim)    #dimension 
print(arr.size)        # element total (size)
print(arr.shape)       #row and column

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
int32
2
60
(10, 6)


In [39]:
#convert 2 or 3d in 1d 
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [46]:
list=[[1,5,2],[4,5,6]]
arr=np.array(list)
arr

array([[1, 5, 2],
       [4, 5, 6]])

In [ ]:
arr.T.shape        #transpose shape

(3, 2)

In [ ]:
arr.T       # generate transpose array

array([[1, 4],
       [5, 5],
       [2, 6]])